name = "cornish_git"
main = "./.output/server/index.mjs"
compatibility_date = "2025-09-24"

[[d1_databases]]
binding = "DB"
database_name = "cornish_db"
database_id = "e31f0586-15cf-4a30-8e34-d3e79915ec53"

[[durable_objects.bindings]]
name = "DO"
class_name = "CornishDO"
script_name = "do_worker"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "pruebas"

[[migrations]]
tag = "v1"
new_classes = [ "CornishDO" ]